title: Jun's image signal processing study blog [영상처리 공부 블로그]
author: amumu79
email: mjw5554@naver.com
description: > # this means to ignore newlines until "baseurl:"
  영상처리/딥러닝/논문조사

# social links
github_username:  amumu79 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
